
out_dir: tinycd
model: TinyCD

criterion: BCE
out_type: logits
# Optimizer
optimizer: Adamw
lr: 0.001
weight_decay: 0.01

schedulers:
  - name: CosineAnnealingLR
    T_max: 100

tinycd_model:
  bkbn_name: 'efficientnet_b4'
  pretrained: True
  output_layer_bkbn: '3'
  freeze_backbone: False

device: cuda:3
batch_size: 1